name: 'Android Build Chapters'
on:
  pull_request:
    branches: [ "main" ]
#     tags:
#       - "v*.*.*"
#   workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        target: [android]
        graphics: [VULKAN, OPENGL_ES]
        chapter: [Chapter1, Chapter2, Chapter3, Chapter4, Chapter5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ${{ matrix.chapter }} using ${{ matrix.gfx }} on ${{ matrix.os }}
        run: |
          echo "Building ${{ matrix.chapter }} using ${{ matrix.gfx }} on ${{ matrix.os }} ${{ github.ref_name }}"
          export GFX=${{ matrix.graphics }}
          cd ${{ matrix.chapter }}
          chmod 755 gradlew
          ./gradlew assembleDebug
