name: 'Build End of Chapter Archives'
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./build-eoc-archs.sh
      - name: Upload End of Chapter Archives
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/eoc_archs/Chapter2.zip
            ./build/eoc_archs/Chapter3.zip
            ./build/eoc_archs/Chapter4.zip
            ./build/eoc_archs/Chapter5.zip